### ISSUE TITLE
Connect Frontend and Backend

### ISSUE THREAD

**Issue by rezbee-dev** [EastWestCollab/samba#15]
**Goal**
- Configure Vite so API calls are proxied to the backend port

**Tasks**
- Modify `vite.config.ts` and add `proxy` to `/api`
- Create dummy page to render contents from `/api/health`

**Criteria**
- `http://localhost:{FRONTEND_PORT}/health` displays renders contents from `http://localhost:{BACKEND_PORT}/api/health`

Notes:

![Image](https://user-images.githubusercontent.com/131298724/235016591-6e9920d2-387e-4f30-95dd-6c25d5eda243.png)

**Comment by monocle** [comment]
With different Docker containers, we'll have a compose.yml file in the project root directory that can do more port configuration and setup a network for the containers.

**Comment by monocle** [comment]
One thing to be aware of, currently I am using MSW for frontend dev. This intercepts fetch calls to the backend and uses mocks defined in the frontend code base. In order to preserve this and allow full integration testing, we'll probably need to setup different env vars. Here's the frontend code that we'll need to adjust:

https://github.com/EastWestCollab/samba/blob/bfab969b00da526ccf528c68c5c5d6977f9da128/frontend/src/main.tsx#L8-L12
